### ISSUE TITLE
Testing & Pentesting frameworks

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [IFS4205-2018-Sem1-Team1/first-report#13]

**Comment by Zhiyuan-Amos** [comment]
Fixed by #24

**Comment by Zhiyuan-Amos** [comment]
Turns out, not really.

![image](https://user-images.githubusercontent.com/19281514/44821716-b11e7500-ac29-11e8-9740-3643e9cccba4.png)

We still need to add the segment on [pentesting](https://medium.com/@jeremy.trinka/five-pentesting-tools-and-techniques-that-sysadmins-should-know-about-4ceca1488bff).

@gngster will you be able to work on this?

**Comment by gngster** [comment]
@chilipadiboy  can you help write in your stuff about the tool you used? :) you mentioned that time that we can use it for pentesting right? I can only work on this part late tonight so if there are any edits to be made i will make them tonight thanks adeeb!!
