### ISSUE TITLE
Database information

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [IFS4205-2018-Sem1-Team1/first-report#7]
I recall there's some diagram to draw what kind of information is being stored in each table, from CS2102

**Comment by chk1994** [comment]
Oops haha ok will do next time. Never use git before so idk what are the norms sorry!

**Comment by Zhiyuan-Amos** [comment]
Oh ok! We can show it to you tmr ba. Also you can include the tool that you used to generate the ER diagram, and whether you have the raw file (example using PowerPoint to create images, so the raw file is .Pptx)

**Comment by chk1994** [comment]
That will be great and really helpful thanks! I use an online tool (draw.io) and its a .xml file so anyone can edit it too

**Comment by Zhiyuan-Amos** [comment]
> I use an online tool (draw.io) and its a .xml file so anyone can edit it too

Yup maybe we can document it somewhere (maybe inside the database_design.md after #23 is merged?) so that other people can know what tool you used and to allow us to easily edit in the future too :)

**Comment by Zhiyuan-Amos** [comment]
Read this from one of the [readings](http://kau.diva-portal.org/smash/get/diva2:1043735/FULLTEXT01.pdf) from project.pdf:

> The data should be kept only for the necessary time to accomplish the initial purpose. User should be able to check when data is deleted.

I'm not sure whether this is referring to "Data visibility". If so, then I think for each `Record`, there's a `VisibleRecord` which has an additional field called something like `visibleTill`, then, after that particular date, the doctor etc will automatically be no longer able to view the record. (my idea is bad database design, I'm just saying a rough idea).

What do you think?

**Comment by Zhiyuan-Amos** [comment]
Also, the database needs to store authentication stuff, including the `salt` value :)

**Comment by Zhiyuan-Amos** [comment]
Basically, just settle the entire `database_design.md`
